businessName: Ina Lubbers-Lensink - Kleding op Maat
shortName: Kleding op maat - Ina Lubbers
phoneDisplay: 0544-377162
phoneTel: "+31544377162"
street: Zilverbekendijk 4
postalCode: 7122 PX
city: Aalten
region: Gelderland
country: NL
serviceArea:
  - Aalten
  - Lichtenvoorde
  - Winterswijk
  - Bredevoort
  - Doetinchem
  - Achterhoek
seoDescription: Wekelijkse naailessen, workshops of op zoek naar kleding op maat? Met veel enthousiasme en kennis van zaken maakt Ina Lubbers van ieder lapje stof iets moois. Atelier in Aalten, Achterhoek.
