businessName: Ina Lubbers-Lensink - Kleding op Maat
shortName: Kleding op maat - Ina Lubbers
phoneDisplay: 06-25277403
phoneTel: "+31625277403"
street: Zilverbekendijk 4
postalCode: 7122 PX
city: Aalten
region: Gelderland
country: NL
serviceArea:
  - Aalten
  - Lichtenvoorde
seoDescription: Wekelijkse naailessen, workshops of op zoek naar kleding op maat? Met veel enthousiasme en kennis van zaken maakt Ina Lubbers van ieder lapje stof iets moois.
